### ISSUE TITLE
Question About Book, BookDto

### ISSUE THREAD

**Issue by GgEggRgg** [babybeb/users-used-book-store#16]
Book에는 생성자가 없고, BookDto에는 생성자는 있는데 변경 수단이 없습니다.
Book의 정보를 수정하고 싶으면 어떻게 해야하는것이 좋을까요?

**Comment by babybeb** [comment]
Book 정보를 수정할 필요가 있나요? 외부 API에서 받아오는 Book 정보를 그대로 사용하는 걸로 알고 있는데... 수정이 필요한 예가 필요합니다.
