### ISSUE TITLE
상품 수정기능에 관해서(Item, Sale)

### ISSUE THREAD

**Issue by GgEggRgg** [babybeb/users-used-book-store#24]
상품 수정 기능을 Sale쪽에서 만들려고 보니까 대부분의 상품관련 정보가 Item에 있더라구요.
그대로 Sale쪽에서 만들까요? 아니면 Item으로 넘길까요?
@babybeb

**Comment by babybeb** [comment]
상품 수정 기능은 ItemRepository의 메서드를 활용하여 SaleService에서 담당하는 것이 맞다고 생각됩니다.

**Comment by GgEggRgg** [comment]
아뇨 다른 의견은 없어요 그렇게 할게요
