### ISSUE TITLE
거래 상태 변경 method 추가와 관련된 질문

### ISSUE THREAD

**Issue by babybeb** [babybeb/users-used-book-store#60]
현재 Item 거래 상태 변경에 관련된 기능은 SaleController의 ChangeSaleStatus와 Item domain의 changeDealStatus에 집중되어 있습니다. 하지만 기능 구현을 위해 controller에서 직접 domain에 접근하다보니 Item의 거래상태가 판매완료로 변경되는 즉시 추가되어야 하는 Purchase의 기능 구현이 어렵습니다. 이에 아래와 같은 method를 ItemService에 구현하고, SaleController의 ChangeSaleStatus에서도 domain의 method에 직접 접근하는 대신 ItemService의 method를 이용했으면 하는데, 이것에 대해 어떻게 생각하시나요?

    @Transactional
    public void changeDealStatus(Long buyerId, Long itemId, String dealStatus) {
        Item findItem = itemRepository.findOne(itemId);
        
        if (dealStatus.equals("COMP")) {
            purchaseService.savePurchase(buyerId, findItem);
        }
       
        findItem.changeDealStatus(dealStatus);
    }

**Comment by GgEggRgg** [comment]
네 그렇게하면 좋을거같네요
